# Generated by Django 4.1.5 on 2023-09-25 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item_library", "0002_alter_item_rarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="rarity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Common"),
                    (2, "Uncommon"),
                    (3, "Rare"),
                    (4, "Very Rare"),
                    (5, "Legendary"),
                    (6, "Artifact"),
                ],
                default=1,
                null=True,
                validators=[django.core.validators.MaxValueValidator(6)],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="value",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
