# Generated by Django 4.1.5 on 2023-10-04 11:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item_library", "0003_alter_item_description_alter_item_rarity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "school",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Abjuration"),
                            (2, "Conjuration"),
                            (3, "Divination"),
                            (4, "Divination"),
                            (5, "Evocation"),
                            (6, "Illusion"),
                            (7, "Necromancy"),
                            (8, "Transmutation"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Cantrip"),
                            (1, "1st"),
                            (2, "2nd"),
                            (3, "3rd"),
                            (4, "4th"),
                            (5, "5th"),
                            (6, "6th"),
                            (7, "7th"),
                            (8, "8th"),
                            (9, "9th"),
                        ],
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
